Repository GDSC-IIIT-Kalyani/Typing-Speed-Test, pull requests merged in 2022-10, with the labels that each got.

#8 Updated Contributing.md
  Contributing.md
Labels: hacktoberfest#accepted

#13 indentation issue solved
  Speed typing.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#11 Updated Readme.md file
  Readme.md
Labels: hacktoberfest-accepted, hacktoberfest2022

#14 Update Readme.md
  Readme.md
Labels: hacktoberfest-accepted, level-1
